### ISSUE TITLE
Syncing loop

### ISSUE THREAD

**Issue by dazWiLLiE** [c2FmZQ/c2FmZQ#3]
Hi again.

I've encountered a sync loop problem.

Uploading file 1 out of 21. When its finished (21/21) it immediately restarts with 1/21 again. It's been doing that since yesterday evening :/

Out of a little more than 1000 images/movies, it's only those 21. Larger movies I think.

```
docker logs -f c2fmzq-server
server/files.go:53] POST /v2/sync/upload (UserID:xxxxxxxxxxx)
server/files.go:53] POST /v2/sync/upload (UserID:xxxxxxxxxxx)
server/files.go:53] POST /v2/sync/upload (UserID:xxxxxxxxxxx)
```

This repeats in nginx log:
`2021/12/14 14:33:26 [error] 493#493: *35494 client intended to send too large chunked body: 134217728+1048576 bytes, client: xx.xx.xx.xx, server: xxxx.*, request: "POST /v2/sync/upload HTTP/1.1", host: "xxxxxxx.xxxxxxxxx.xxx"
`
Do I need to increase some buffer in nginx?

**Comment by dazWiLLiE** [comment]
I increased client_max_body_size in nginx, lets see if that fixes things.

I'm having a monologue with myself now :)

**Comment by rthellend** [comment]
Yes, you'll need to configure nginx to allow body sizes at least as large as your largest file. c2fmzq-server doesn't limit the upload size.

**Comment by dazWiLLiE** [comment]
Yes, it works now :)
