### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by n00b42** [c2FmZQ/c2FmZQ#4]
Could you maybe publish your docker image on docker hub, or may I do that?
(In order to use the image on my Unraid NAS)

**Comment by rthellend** [comment]
You are certainly welcome to publish your own docker image. I might do it too if there's enough demand for it.

**Comment by n00b42** [comment]
Ok, thank you. If its of any interest:
Published a (http only) image at: https://hub.docker.com/repository/docker/n00b42/c2fmzq-server
Which can be used with Unraid using the following template: https://github.com/n00b42/unraid-docker-templates/blob/main/c2fmzq-server.xml

**Comment by rthellend** [comment]
I created https://hub.docker.com/r/c2fmzq/c2fmzq-server.

```
docker pull c2fmzq/c2fmzq-server:latest
```
