### ISSUE TITLE
PWA: video upload does not work

### ISSUE THREAD

**Issue by n00b42** [c2FmZQ/c2FmZQ#49]
![grafik](https://github.com/c2FmZQ/c2FmZQ/assets/6792900/ae96e46c-a7f8-4237-a722-5e0ce59736c3)

While it says "preparing", nothing ever happens.
Note: file size does not seem to matter

**Comment by rthellend** [comment]
Does it show anything in the javascript console?

**Comment by n00b42** [comment]
You are right, forgot to check, there is a JS error:
~~~
Refused to load media from 'blob:https://stingle.domain.tld/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.
~~~

**Comment by n00b42** [comment]
Still some issue in v0.4.12 with Firefox 120.0:
GUI:
~~~
Name: 5MB_2s.mp4
Size: 5.47 MiB
Status: ...
~~~
Log:
~~~
Medien-Ressource blob:https://stingle.domain.tld/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa konnte nicht dekodiert werden. stingle.domain.tld
Medien-Ressource blob:https://stingle.domain.tld/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa konnte nicht dekodiert werden, Fehler: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006) stingle.domain.tld
~~~

**Comment by n00b42** [comment]
For reference in Chrome I get randomly an instant `TypeError: Failed to fetch` (roughly 20-50%)
~~~
Start UI
c2fmzq-client.js:1808 SW ping
c2fmzq-client.js:2274 SW streaming upload is supported by browser
c2fmzq-client.js:2301 SW Upload of 5MB_2s.mp4 failed TypeError: Failed to fetch
    at c2FmZQClient.uploadFile_ (c2fmzq-client.js:2377:12)
    at async c2fmzq-client.js:2297:13
ui.js:545 Show Error TypeError: Failed to fetch
    at c2FmZQClient.uploadFile_ (c2fmzq-client.js:2377:12)
    at async c2fmzq-client.js:2297:13
~~~
If the error does not occur (simply repeatetly pressing upload) then it works regardlessly of file size.

**Comment by rthellend** [comment]
`Failed to fetch` is the browser's way of saying the request to the server failed.

This might be related to your other problem? (https://github.com/c2FmZQ/c2FmZQ/discussions/54)

I think the `NS_ERROR_DOM_MEDIA_METADATA_ERR` means that firefox doesn't understand the file format that you're trying to upload. So, the app is failing to create a thumbnail for it.

Do you get this error for all video files, or just some?

**Comment by n00b42** [comment]
For testing I used the sample files provided from: https://file-examples.com/index.php/sample-video-files/
(Windows 10, Firefox 120.0)

- avi: did **not** work
~~~
23:47:35.198 HTTP-Content-Type "video/avi" ist not supported.  Load of media resource blob:https://stingle.domain.tld/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa fehlgeschlagen. [stingle.domain.tld](https://stingle.domain.tld/)
23:47:36.221 Cannot play media. No decoders for requested formats: video/avi
~~~
- mov: **works** (but browser/serviceworker log still shows some error)
~~~
00:04:21.189 [Exception... "Component returned failure code: 0x8050000e (NS_ERROR_ILLEGAL_INPUT) [nsIConverterInputStream.readString]"  nsresult: "0x8050000e (NS_ERROR_ILLEGAL_INPUT)"  location: "JS frame :: resource://gre/modules/WebRequestUpload.sys.mjs :: readString :: line 241"  data: no] WebRequestUpload.sys.mjs:241:12
    readString resource://gre/modules/WebRequestUpload.sys.mjs:241
    readAllStrings resource://gre/modules/WebRequestUpload.sys.mjs:273
    next self-hosted:1390
    getParts resource://gre/modules/WebRequestUpload.sys.mjs:292
    next self-hosted:1390
    parseMultiPart resource://gre/modules/WebRequestUpload.sys.mjs:318
    parseFormData resource://gre/modules/WebRequestUpload.sys.mjs:406
    createFormData resource://gre/modules/WebRequestUpload.sys.mjs:447
    createRequestBody resource://gre/modules/WebRequestUpload.sys.mjs:537
    runChannelListener resource://gre/modules/WebRequest.sys.mjs:998
    forEach self-hosted:1929
    runChannelListener resource://gre/modules/WebRequest.sys.mjs:931
    observe resource://gre/modules/WebRequest.sys.mjs:751
00:04:27.844 NS_ERROR_FAILURE 
~~~
- mp4 (h264): **works**
- ogg: **works**
- webm: **works**
- wmv: did **not** work
~~~
23:47:35.198 HTTP-Content-Type "video/x-ms-wmv" ist not supported.  Load of media resource blob:https://stingle.domain.tld/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa fehlgeschlagen. [stingle.domain.tld](https://stingle.domain.tld/)
23:47:36.221 Cannot play media. No decoders for requested formats: video/x-ms-wmv
~~~

- mp4 (**h265**): did **not** work
( used the sample file from: https://oliverx.link/samples/sample-mp4-download/hd-mp4/download-free-mp4-hevc-h265-fullhd-1080p-24fps-aac-sample/ )
~~~
Media resource blob:https://stingle.domain.tld/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa could not be decoded.
Media resource blob:https://stingle.domain.tld/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa could not be decoded, Error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)
~~~

The last one explains some issue with the videos recorded by my smartphone (as they all are recorded as h265)

**Comment by n00b42** [comment]
So the browser needs to be able to decode the video for the thumbnails, even though the app might offer support for a different set of formats.

**Comment by rthellend** [comment]
We can probably update the PWA to create a generic thumbnail when that happens. That thumbnail would be an image with just text.

The browser still won't be able to playback that video though. It might work on other devices, but there's no way to update the thumbnail after the file is uploaded.

That's the downside of doing client side encryption. We can't use external services for transcoding. All the work has to be done by the client.

**Comment by n00b42** [comment]
I understand, I just was not aware that FF does not support H265 (apparently for licensing reasons), Chrome seems to support it, but only if hardware support is given (which most modern hw provides)

**Comment by rthellend** [comment]
v0.4.13 should let you upload video files that are not supported by the current browser.

**Comment by n00b42** [comment]
I assume allowing to manually provide a screenshot would be way to much work (and not parallel to the mobile app)

**Comment by rthellend** [comment]
It would be a lot of work. Feel free to put in a separate feature request, but no promises.

**Comment by n00b42** [comment]
> v0.4.13 should let you upload video files that are not supported by the current browser.

Tested it and works.

I noticed that the problem applies to all meta data (i.e. video length as well) as well.


Thanks for all the clarification and help and for the update. I think we might close this issue.
