### ISSUE TITLE
Publishing on the official F-Droid repository

### ISSUE THREAD

**Issue by alexanderadam** [c2FmZQ/c2FmZQ#7]
Would you consider [adding the app for c2FmZQ](https://github.com/c2FmZQ/stingle-photos-for-self-hosted-server) to the official F-Droid repository?
This way people would see it and can get updates easily.

There's also [some documentation on what is allowed](https://f-droid.org/en/docs/) but I guess it should be fine as long there are no proprietary extensions.
It's possible to [create a RFP on the F-Droid GitLab repository](https://gitlab.com/fdroid/rfp/-/issues/new).

This will probably be even more relevant when there's [an official Docker container](https://github.com/c2FmZQ/c2FmZQ/issues/4) that can be easily installed.

Thank you for your fork, this already looks impressive.

**PS:** Maybe you could activate [the "issues" tab in the app repository settings under "Features"](https://github.com/c2FmZQ/stingle-photos-for-self-hosted-server/settings#features)?

**Comment by rthellend** [comment]
Thank you for your interest!

> Would you consider [adding the app for c2FmZQ](https://github.com/c2FmZQ/stingle-photos-for-self-hosted-server) to the official F-Droid repository? This way people would see it and can get updates easily.

I would totally be in favor of that. It would be great if someone volunteered to manage that :)

> This will probably be even more relevant when there's [an official Docker container](https://github.com/c2FmZQ/c2FmZQ/issues/4) that can be easily installed.

Likewise, I'm all in favor. If only someone could take the lead on that.

> Thank you for your fork, this already looks impressive.

> **PS:** Maybe you could activate [the "issues" tab in the app repository settings under "Features"](https://github.com/c2FmZQ/stingle-photos-for-self-hosted-server/settings#features)?

Done.

**Comment by alexanderadam** [comment]
Thank you for the fast response and for activating the issues tab.
Is `c2FmZQ` the official app name? It would be pretty difficult to memoize.
Or is it `Stingle photos for self hosted server`? It could lead to some weird copyright/branding quirk.
Or is it something else?

**Comment by rthellend** [comment]
We certainly don't want to run into copyright disputes. At the same time, we want to be very clear that the Android app is fundamentally the same as the `Stingle Photos` app with only minor changes. This is all GPL v3 code.

For now, I'd be OK with just publishing it as `c2FmZQ` with a description that emphasizes the above, and links to the `README` on github.

**Comment by alexanderadam** [comment]
Okay, is [this](https://gitlab.com/fdroid/rfp/-/issues/2135) okay for you?
Also I'm closing this issue here, since we should continue further details [on the app repo](https://github.com/c2FmZQ/stingle-photos-for-self-hosted-server/issues/4).
