### ISSUE TITLE
Limit storage size per user?

### ISSUE THREAD

**Issue by poVoq** [c2FmZQ/c2FmZQ#8]
Since the official app seems to support this via their payment tiers, can this also be done in this backend to avoid having a user upload hundreds of gigs of photos without permission?

Edit: looks like this is possible but undocumented? https://github.com/c2FmZQ/c2FmZQ/blob/main/HOWTO-AWS.md#show-users-set-quotas-etc

**Comment by rthellend** [comment]
You can set quotas with the inspect command, or from the experimental progressive web app.
